### ISSUE TITLE
Feedback for "SAP Business Technology Platform"

### ISSUE THREAD

**Issue by jrbpraven** [SAP-docs/btp-cloud-platform#8] opened 2021-12-08 01:25 UTC
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/6a2c1ab5a31b4ed9a2ce17a5329e1dd8.html?locale=en-US

Hi, I tried to download PDF Version of SAP BTP documentation, but I didn't get any response. I see this URL when I chose the option Download PDF/Download PDF:

https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/undefined/doc/bd6250c40c9c4c5391e3009a6f26dc3b/Cloud/en-US/SAP_Cloud_Platform.pdf

I could see these messages in my Browser console:

LAUNCH: local_sap_s: sap_s.referrer (1):  undefined
launch-8b3c5ca29b9e.min.js:9 LAUNCH: local_sap_s: sap_s.referrer (2):  https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/6a2c1ab5a31b4ed9a2ce17a5329e1dd8.html?locale=en-US
VM190:3 SWA RUNNING
VM193:2 LAUNCH: kaltura object listener attempt 1
VM193:2 LAUNCH: kaltura object listener attempt 2
VM193:2 LAUNCH: kaltura object listener attempt 3
VM193:2 LAUNCH: kaltura object listener attempt 4
VM193:2 LAUNCH: kaltura object listener attempt 5
VM193:2 LAUNCH: kaltura object listener attempt 6
VM193:2 LAUNCH: kaltura object listener attempt 7
VM193:2 LAUNCH: kaltura object listener attempt 8
VM193:2 LAUNCH: kaltura object listener attempt 9
VM193:2 LAUNCH: kaltura object listener attempt 10
VM193:2 LAUNCH: no kaltura widget detected

In the old version of the documentation it always worked, but currently it doesn't works...
 
Could you check it please?

**Comment by nikolasimeonov77** [comment] 2021-12-08 16:20
Hi José,
Thanks for the feedback, and we will look into this issue. In the meantime, you can open and download the PDF from the following URL: https://help.sap.com/doc/bd6250c40c9c4c5391e3009a6f26dc3b/Cloud/en-US/SAP_Cloud_Platform.pdf.

Sincerely,
Nikola

**Comment by KathrinLuecke** [comment] 2021-12-09 13:17
@nikolasimeonov77 Hi Nikola, the issue is known and currently being fixed (https://sapjira.wdf.sap.corp/browse/DPS-12424). Best regards, Kathrin

**Comment by jrbpraven** [comment] 2021-12-16 10:28
> Hi José, Thanks for the feedback, and we will look into this issue. In the meantime, you can open and download the PDF from the following URL: https://help.sap.com/doc/bd6250c40c9c4c5391e3009a6f26dc3b/Cloud/en-US/SAP_Cloud_Platform.pdf.
> 
> Sincerely, Nikola

Ok Nikola, many thanks.

**Comment by nikolasimeonov77** [comment] 2022-01-05 08:42
Thank you for reporting this issue. It is fixed now.

Sincerely,
Nikola

**Closed by nikolasimeonov77** 2022-01-05 08:42 UTC
Labels: contribution, follow-up-with/dev, type/linking, ua-review

**Comment by jrbpraven** [comment] 2022-01-07 11:06
https://people.sap.com/josereynaldo.bautistapalomino
