### ISSUE TITLE
No languages listed

### ISSUE THREAD

**Issue by tobiashofmann** [SAP-docs/btp-cloud-platform#229] opened 2024-06-27 13:31 UTC
### Issue description

The site lists no programming languages:

"The following programming languages are available in the environments:"

Followed by no list of programming languages.

<img width="1708" alt="image" src="https://github.com/SAP-docs/btp-cloud-platform/assets/2013590/b84c86f0-d8db-4278-9db6-d1db20309a30">

Expected result:
List the available programming languages per environment.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Programming Languages

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/730d82d3e2054aef84553f636c52ec49.html

**Comment by Peteva** [comment] 2024-06-28 07:41
Hi @tobiashofmann, thank you for your feedback! We will look into it and get back to you when it's fixed.

**Comment by nikolasimeonov77** [comment] 2024-07-01 06:03
Hi @tobiashofmann,
Sorry for the caused inconvenience and for reporting it. The documentation is now fixed at https://help.sap.com/docs/btp/sap-business-technology-platform/programming-languages.

**Closed by nikolasimeonov77** 2024-07-01 06:03 UTC
Labels: type/content-gaps, type/visualization, ua-review
