### ISSUE TITLE
Feedback for "Assign Roles in the Kyma Environment"

### ISSUE THREAD

**Issue by jalibu** [SAP-docs/btp-cloud-platform#103] opened 2022-09-23 06:26 UTC
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/148ae38b7d6f4e61bbb696bbfb3996b2.html

This page is outdated.

**Comment by DavidMitreski5** [comment] 2022-09-23 09:53
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by grego952** [comment] 2022-09-27 09:45
Hi @jalibu 
Thank you for the issue. Can you provide more details about the problem? Which part of the documentation seems to be outdated?
Thank you!

**Comment by grego952** [comment] 2022-10-13 07:44
I added the missing step in the Procedure, which I think is what @jalibu asks for. If something else should be updated, please reopen the issue and provide the details. Thank you!

**Comment by jalibu** [comment] 2022-10-13 08:31
@grego952 you know that the Cluster Roles kyma-developer etc are deprecated? This guide describes a namespace-isolation concept which is no longer valid (since Kyma 2.0)

**Comment by jalibu** [comment] 2022-10-13 08:43
Please re-open this ticket. The article will still cause confusion in its latest version

**Comment by DavidMitreski5** [comment] 2022-10-21 07:23
Hello @grego952, could you please revisit this ticket? It has been almost a month since it's opened, I think we should resolve this problem.

**Comment by jalibu** [comment] 2022-10-21 11:20
@grego952 nope, nothing has improved. The article still mentions kyma-developer role which is legacy and useless

**Comment by grego952** [comment] 2022-10-25 05:58
Thanks for the feedback!
I removed all the occurrences of the kyma-developer role. You can find the updated doc [here](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/148ae38b7d6f4e61bbb696bbfb3996b2.html?locale=en-US&state=DRAFT&version=Dev). @jalibu, please take a look.

**Comment by grego952** [comment] 2022-10-25 06:01
Thank you for your feedback!
I removed all the occurrences of the kyma-developer role. You can find the updated doc [here](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/148ae38b7d6f4e61bbb696bbfb3996b2.html?locale=en-US&state=DRAFT&version=Dev). @jalibu, please take a look when you have a moment.

**Comment by grego952** [comment] 2022-10-26 07:55
I spoke with @jalibu today, and he confirmed that the last version of the doc is much better now, and we can close the issue.
The updated version should be published with the next takt release (03.11.2022).
Thank you!

**Closed by grego952** 2022-10-26 07:55 UTC
Labels: type/outdated, ua-review, environment/kyma

**Comment by je-hal** [comment] 2022-10-26 12:32
@grego952 Please remember to assign the `contribution` tag for valuable contributions.  For issues, this has to be done manually. This time, I'll do it for you. 

Thanks
